security:
    basic:
      enabled: false


  management:
    security:
      enabled: false


  logging:
    level:
      io:
        pivotal: DEBUG


  greeting:
    displayFortune: false # <----Change to true


  quoteServiceURL: http://quote-service-dev.cfapps.io/quote
